# Generated by Django 3.1.4 on 2020-12-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melcom_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
    ]
