# Generated by Django 3.1.4 on 2020-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melcom_one', '0004_auto_20201211_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=1),
        ),
    ]
