# Generated by Django 3.1.4 on 2020-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melcom_one', '0005_auto_20201211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
